-- MySQL Script generated by MySQL Workbench
-- Fri Nov 24 19:30:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conexaomais
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema conexaomais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conexaomais
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conexaomais` DEFAULT CHARACTER SET utf8 ;
USE `conexaomais` ;

-- -----------------------------------------------------
-- Table `conexaomais`.`tb_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_perfil` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL COMMENT '1=administracao\\n2=prefeito comunitario\\n3-suporte\\n',
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `idperfil` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_tb_usuario_tb_perfil1_idx` (`idperfil` ASC),
  CONSTRAINT `fk_tb_usuario_tb_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `conexaomais`.`tb_perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_prefeito_comunitario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_prefeito_comunitario` (
  `idprefeitura` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_prefeito` VARCHAR(45) NOT NULL,
  `cpf_prefeito` VARCHAR(45) NOT NULL,
  `dt_nasc_prefeito` DATE NOT NULL,
  `tel_prefeito` VARCHAR(15) NOT NULL,
  `genero` INT(11) NOT NULL COMMENT '1=masculino\\n2=feminino\\n3=outros',
  `endereco_prefeito` VARCHAR(100) NOT NULL,
  `numero_registro_prefeito` VARCHAR(45) NOT NULL,
  `data_criacao_prefeito` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idprefeitura`),
  UNIQUE INDEX `cpf_Prefeito_UNIQUE` (`cpf_prefeito` ASC),
  UNIQUE INDEX `tel_prefeito_UNIQUE` (`tel_prefeito` ASC),
  UNIQUE INDEX `numero_registro_prefeito_UNIQUE` (`numero_registro_prefeito` ASC),
  INDEX `fk_tb_prefeito_comunitario_tb_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_tb_prefeito_comunitario_tb_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `conexaomais`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_status` (
  `idstatus` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_tipo_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_tipo_projeto` (
  `idtipo_projeto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_projeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_tipo_regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_tipo_regiao` (
  `idtipo_regiao` INT(11) NOT NULL AUTO_INCREMENT,
  `regiao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_regiao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_projeto` (
  `idprojeto` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `dataHora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idtipo_projeto` INT(11) NOT NULL,
  `idprefeitura` INT(11) NOT NULL,
  `idstatus` INT(11) NOT NULL,
  `idtipo_regiao` INT(11) NOT NULL,
  PRIMARY KEY (`idprojeto`),
  INDEX `fk_tb_projeto_tb_tipo_projeto1_idx` (`idtipo_projeto` ASC),
  INDEX `fk_tb_projeto_tb_prefeito_comunitario1_idx` (`idprefeitura` ASC),
  INDEX `fk_tb_projeto_tb_status1_idx` (`idstatus` ASC),
  INDEX `fk_tb_projeto_tipo_regiao1_idx` (`idtipo_regiao` ASC),
  CONSTRAINT `fk_tb_projeto_tb_prefeito_comunitario1`
    FOREIGN KEY (`idprefeitura`)
    REFERENCES `conexaomais`.`tb_prefeito_comunitario` (`idprefeitura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_projeto_tb_status1`
    FOREIGN KEY (`idstatus`)
    REFERENCES `conexaomais`.`tb_status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_projeto_tb_tipo_projeto1`
    FOREIGN KEY (`idtipo_projeto`)
    REFERENCES `conexaomais`.`tb_tipo_projeto` (`idtipo_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_projeto_tipo_regiao1`
    FOREIGN KEY (`idtipo_regiao`)
    REFERENCES `conexaomais`.`tb_tipo_regiao` (`idtipo_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conexaomais`.`tb_protocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conexaomais`.`tb_protocolo` (
  `idprotocolo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_protocolo` VARCHAR(45) NOT NULL,
  `cpf_protocolo` VARCHAR(45) NOT NULL,
  `dt_nasc_protocolo` DATE NOT NULL,
  `genero_protocolo` INT(11) NOT NULL COMMENT '1=masculino\\n2=feminino\\n3=outros',
  `tel_protocolo` VARCHAR(15) NOT NULL,
  `endereco_protocolo` VARCHAR(100) NOT NULL,
  `SIAPE_protocolo` VARCHAR(9) NOT NULL,
  `data_criacao_protocolo` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idprotocolo`),
  UNIQUE INDEX `cpf_Adm_UNIQUE` (`cpf_protocolo` ASC),
  UNIQUE INDEX `tel_Adm_UNIQUE` (`tel_protocolo` ASC),
  INDEX `fk_tb_sra_tb_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_tb_sra_tb_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `conexaomais`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
